config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis



  resources :collaborators, only: [:create, :new]

  devise_for :users

  resources :users, only: [:show]

  get "welcome/index"

  root 'welcome#index'

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  validates :body, presence: true
  validates :title,
    presence: true,
    uniqueness: { case_sensitve: false, scope: [:year]},
    length: { minimum: 3, maximum: 254}

  enum category: [:adventure, :dual_sport, :sport, :naked,
    :touring, :cruiser, :custom, :dirt, :roadster]

  enum final_drive: [:belt, :chain, :shaft]

  filterrific(
    default_filter_params: { sorted_by: 'title_asc'},
    available_filters: [
      :sorted_by,
      :search_query
    ]
  )

    self.per_page = 20


  scope :search_query, lambda { |query|
    return nil  if query.blank?

    terms = query.downcase.split(/\s+/)

    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(wikis.title) LIKE ? OR LOWER(wikis.manufacture) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  scope :sorted_by, lambda { |sort_option|
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^title_/
      order("wikis.title #{ direction }")
    when /^cylinders_/
      order("wikis.cylinders #{ direction }")
    when /^hp_/
      order("wikis.hp #{ direction }")
    when /^torque_/
      order("wikis.torque #{ direction }")
    when /^displacement_/
      order("wikis.displacement #{ direction }")
    when /^year_/
      order("wikis.year #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  def self.options_for_sorted_by
    [
      ['Title (a-z)', 'title_asc'],
      ['HP (most)', 'hp_desc'],
      ['HP (least)', 'hp_asc'],
      ['Torque (most)', 'torque_desc'],
      ['Torque (least)', 'torque_asc'],
      ['Year (oldest)', 'year_desc'],
      ['Year (newest)', 'year_asc'],
      ['Displacement (most)', 'displacement_desc'],
      ['Displacement (least)', 'displacement_asc'],
      ['Cylinders (most)', 'cylinders_desc'],
      ['Cylinders (least)', 'cylinders_asc'],
    ]
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  include ApplicationHelper
  require 'redcarpet'

  before_action :require_sign_in, except: [:show, :index]
  before_action :is_private_wiki_owner_or_collaborator? , only: [:edit, :update, :destroy]

  def show
    @wiki = Wiki.find(params[:id])
    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, filter_html: true, strikethrough: true, highlight: true, quote: true, footnotes: true)
  end

  def index
    @filterrific = initialize_filterrific(
      Wiki,
      params[:filterrific],
      select_options: {
        sorted_by: Wiki.options_for_sorted_by,
      },
      available_filters: [:sorted_by, :search_query],
    ) or return

    @wikis = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
    rescue ActiveRecord::RecordNotFound => e
      puts "Had to reset filterrific params: #{ e.message }"
      redirect_to(reset_filterrific_url(format: :html)) and return
  end

  def new
    @wiki = Wiki.new
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user_id = current_user.id

    if @wiki.save
      flash[:notice] = "New wiki created!"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "An error occured while trying to create the wiki.  Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    unless Collaborator.find_by(user_id: current_user.id, wiki_id: @wiki.id)
      Collaborator.create!(user_id: current_user.id, wiki_id: @wiki.id)
    end


    if @wiki.save
      flash[:notice] = "Entry was updated"
      redirect_to [@wiki]
    else
      flash.now[:alert] = "An error occured while trying to update the wiki.  Please try again."
      render :new
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "#{@wiki.title} was removed from Motopedia"
      redirect_to wikis_path
    else
      flash[:notice] = "An error occured while attempting to delete the entry.  Please try agian"
      render :show
    end
  end

  private

  def wiki_params
    params.require(:wiki).permit!
  end

  def is_private_wiki_owner_or_collaborator?
    wiki = Wiki.find(params[:id])
    if wiki.private
      unless (wiki_owner(wiki) || is_collaborator?(current_user.id, wiki.id))
        flash[:alert] = "You are not the owner or a collaborator of this private wiki"
        redirect_to [wiki]
      end
    end
  end
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/wikis/_form.html.erb
<script>
  var editor = new EpicEditor({
    base: "<%= asset_path 'epiceditor/themes/base/epiceditor.css' %>",
    preview: "<%= asset_path 'epiceditor/themes/preview/preview-dark.css' %>",
    editor: "<%= asset_path 'epiceditor/themes/editor/epic-dark.css' %>"}).load();
</script>

<%= form_for wiki do |f| %>
  <div class="row">
    <div class="col-sm-5">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: "Enter Name of Motorcyle" %>
      </div>
      <div class="field">
        <%= f.label :power %>
        <%= f.number_field :hp, placeholder: "in HP" %>
      </div>
      <div class="field">
        <%= f.label :torque %>
        <%= f.number_field :torque, placeholder: "in NM" %>
      </div>
      <div class="field">
        <%= f.label :displacement %>
        <%= f.number_field :displacement, placeholder: "in CC" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="field">
        <%= f.label :manufacturer %>
        <%= f.text_field :manufacture, placeholder: "Enter Name of Manufacturer" %>
      </div>
      <div class="field">
        <%= f.label :year %>
        <%= f.number_field :year, placeholder: "Model Year" %>
      </div>
      <div class="field">
        <%= f.label :cylinders %>
        <%= f.select :cylinders, [1, 2, 3, 4, 5, 6] %>
      </div>
      <div class="field">
        <%= f.label :final_drive %>
        <%= f.select :final_drive, ['chain', 'belt', 'shaft'] %>
      </div>
      <div class="field">
        <%= f.label :category %>
        <%= f.select :category, ['adventure', 'dual_sport', 'sport',
          'naked', 'touring', 'cruiser', 'custom', 'dirt', 'roadster'] %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-10">
      <% if is_premium_user? && ( wiki_owner(@wiki) || new_wiki ) %>
        <%= f.label :private? %>
        <%= f.check_box :private %>
      <% end %>
      <div class="markdown">
        <% if new_wiki %>
          <div id="epiceditor">
            <%= f.label :body %>
            <%= f.text_area :body, placeholder: "Enter Motorcyle Description", class: "body", value: "Write description here.  Markdown syntanx accepted." %>
          </div>
        <% else %>
          <div id="epiceditor">
            <%= f.label :body %>
            <%= f.text_area :body, placeholder: "Enter Motorcyle Description", class: "body" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <br />

  <%= f.submit "Save", class: "field" %>
<% end %>

app/views/wikis/_list.html.erb
<div id="filterrific_results">
  <div>
    <%= page_entries_info wikis %>
  </div>
  <% wikis.each do |wiki| %>
    <h4>
      <%= link_to wiki.title, wiki %>
      (<%= wiki.year %>)
    </h4>
  <% end %>
</div>
<%= will_paginate wikis %>

app/views/wikis/create.html.erb
<h1>Wikis#create</h1>
<p>Find me in app/views/wikis/create.html.erb</p>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit Entry</h1>
<%= render partial: "wikis/form", locals: { wiki: @wiki, new_wiki: false } %>
<% if is_premium_user? && wiki_owner(@wiki) %>
  <%= render partial: "collaborators/add_collaborators", locals: {wiki: @wiki.id} %>
<% end %>

app/views/wikis/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="search-box">
        <%= form_for_filterrific @filterrific do |f| %>
        <div class="search">
          Search
          <%= f.text_field(
            :search_query,
            class: 'filterrific-periodically-observed'
          ) %>
        </div>
        <div class="search">
          Sorted by
          <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
        </div>
        <%= render_filterrific_spinner %>
        <% end %>
      </div>
      <div>
        <%= render(
          partial: 'wikis/list',
          locals: { wikis: @wikis }
        ) %>
      </div>
    </div>
  </div>
</div>

app/views/wikis/index.js.erb
<% js = escape_javascript(
  render(partial: 'wikis/list', locals: { wikis: @wikis })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/wikis/new.html.erb
<h1>Add New Motorcyle to Motopedia</h1>
<p>
  Please perform a quick search for the motorcyle that
  you would like to make sure that you are not adding
  a duplicate entry.
 <br /> <br />
  Motopedia is markdown friendly (in the body section).  Please refer to this
  <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet">cheat sheet</a>
  for markdown sytanx.
</p>
<br />

<%= render partial: "wikis/form", locals: { wiki: @wiki, new_wiki: true } %>

app/views/wikis/show.html.erb
  <div class="row">
    <div class="col-sm-12">
      <h1>
        <%= @wiki.title %>
      </h1>
      <% if @wiki.private %>
        <h6>Private Wiki</h6>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <p>
        <%= @markdown.render(@wiki.body).html_safe  %>
      </p>
      <br />
      <h4>Owner/Creator</h4>
      <h5>
        <%= User.find_by(id: @wiki.user_id).email %>
      </h5>
      <br />
      <% if any_collaborators?(@wiki) %>
        <p>
          <h4>Collaborators</h4>
          <ul>
            <% Collaborator.where(wiki_id: @wiki.id).each do |collaborator| %>
              <li>
                <%= User.find_by(id: collaborator.user_id).email %>
              </li>
            <% end %>
          </ul>
        </p>
      <% end %>
    </div>
    <div class="col-sm-4">
        <div class="row edit-delete">
          <div class="col-sm-6 edit">
            <%= link_to "edit entry", edit_wiki_path(@wiki) %>
          </div>
          <div class="col-sm-6 delete">
            <%= link_to "delete entry", @wiki, method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
        </div>
      <table class="table table-striped">
        <tr>
          <td><b>Manufacturer</b></td>
          <td><%= @wiki.manufacture %></td>
        </tr>
        <tr>
          <td><b>Year</b></td>
          <td><%= @wiki.year %></td>
        </tr>
        <tr>
          <td><b>Power</b></td>
          <td><%= @wiki.hp %> hp</td>
        </tr>
        <tr>
          <td><b>Torque</b></td>
          <td><%= @wiki.torque %> nm</td>
        </tr>
        <tr>
          <td><b>Displacement</b></td>
          <td><%= @wiki.displacement %>cc</td>
        </tr>
        <tr>
          <td><b>Cylinders</b></td>
          <td><%= @wiki.cylinders %></td>
        </tr>
        <tr>
          <td><b>Final Drive</b></td>
          <td><%= @wiki.final_drive %></td>
        </tr>
        <tr>
          <td><b>Category</b></td>
          <td><%= @wiki.category %></td>
        </tr>
      </table>
    </div>
  </div>

app/views/wikis/update.html.erb
<h1>Wikis#update</h1>
<p>Find me in app/views/wikis/update.html.erb</p>