config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis



  resources :collaborators, only: [:create, :new]

  devise_for :users

  resources :users, only: [:show]

  get "welcome/index"

  root 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  @stripe_btn_data = {
    key: "#{ Rails.configuration.stripe[:publishable_key] }",
    description: "Premium Membership - #{current_user.email}",
    amount: 500
  }
  end

  def create

    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    subscribe = Stripe::Subscription.create(
      :customer => customer.id,
      :plan => "premium-plan"
    )

    current_user.update(sub_id: subscribe.id, account: 'premium')

    flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
    redirect_to root_path

    rescue Stripe::CardError => e
      flash[:alert] = e.message
      redirect_to new_charge_path
  end

  def destroy
    subscription = Stripe::Subscription.retrieve(current_user.sub_id)
    subscription.delete
    current_user.update(account: 'standard')
    private_wikis = Wiki.where(user_id: current_user.id)
    private_wikis.each do |wiki|
      wiki.update(private: false)
    end
    flash[:notice] = "You subscription has ended and you will no longer be billed"
    redirect_to root_path
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<h1>Become a Premium User at Motopedia</h1>
<h4> What do you get with your Premium Membership?</h4>
<ul>
  <li>
    Create private wikis that only you can edit!
  </li>
  <li>
    Get a virtual 'High-Five' once a month!
  </li>
  <li>
    The knowledge that you are helping to support an
    independent project.
  </li>
</ul>
<p>
  Becoming a Premium Member at Motopedia is only $5 per month.
  An amount of $5 will be charged to your credit card once a month.
  You can cancel any time you like.  *note: When you cancel
  any private wikis that you have created will become public.
</p>
<div class="pull-right">
  <%= form_tag charges_path do %>
    <h4>Subscribe Now!</h4>
    <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
  <% end %>
</div>