config/routes.rb
Rails.application.routes.draw do

  resources :charges, only: [:new, :create, :destroy]

  resources :wikis



  resources :collaborators, only: [:create, :new]

  devise_for :users

  resources :users, only: [:show]

  get "welcome/index"

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motopedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container top-bar">
    <ul class="nav nav-tabs">
      <% if current_user && is_standard_user? %>
        <div class="pull-left premium">
          <%= link_to "Become a Premium User", new_charge_path %>
        </div>
      <% end %>
      <% if current_user && is_premium_user? %>
      <div class="pull-left premium">
        <%= link_to "Cancle Premium Membership", charge_path(current_user), method: :delete, data: {confirm: "Are you sure that you want to cancel your subscription? NOTE: All of your private wikis will become public."} %>
      </div>
      <% end %>
      <div class="pull-right user-info">
        <% if current_user %>
        <div>
          <%= link_to "#{current_user.email}", user_path(current_user) %> |
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
        </div>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
      </div>
    </ul>
  </div>
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-2 sidebar">
      <ul class="nav nav-tabs sidebar">
        <li>
          <%= link_to "Motopedia", root_path %>
        </li>
        <% if current_user %>
          <li>
            <%= link_to "My Profile", user_path(current_user) %>
          </li>
        <% end %>
        <li>
          <%= link_to "Motorcycle Index", wikis_path %>
        </li>
        <li>
          <%= link_to "Add Motorcyle", new_wiki_path %>
        </li>
      </ul>
    </div>
    <div class="col-sm-10">
      <%= yield %>
    </div>
  </div>
</div>


</body>
</html>